### ISSUE TITLE
Dask from parallel session to Big data session?

### ISSUE THREAD

**Issue by bclaremar** [UPPMAX/HPC-python#24]
https://uppmax.github.io/HPC-python/day2/parallel.html#dask

May I take this part?

You may however mention the task scheduler possibilities.
https://docs.dask.org/en/stable/scheduling.html

Whereas I am more interested in the parts mentioned in the main page:
https://www.dask.org/

Or do you think it is too much interwoven?

**Comment by pojeda** [comment]
Take it, if so you can also take the "scheduler possibilities" you mentioned. Then, I will focus only on the Parallelization parts.

**Comment by bclaremar** [comment]
OK, I take it. Not totally logical to big data but logical to mention a possibility with DASK!

**Comment by bclaremar** [comment]
you can safely remove the dask parts in your session @pojeda
