### ISSUE TITLE
Needed packages for the exercises

### ISSUE THREAD

**Issue by bclaremar** [UPPMAX/HPC-python#42]
Please inform here what is needed and, if possible, the different demands for different systems.
@bclaremar will gather the packages for the users to install as virtual environments on their cluster

**Comment by bbrydsoe** [comment]
I am using: 
Python/3.11.8 on UPPMAX
Python/3.11.3 on HPC2N
Python/3.11.5 on LUNARC
Python/3.10.5 on NSC

I have found working packages with these Python versions for: pandas, matplotlib, numpy, scipy (many are in SciPy-bundle). I also have working tkinter for this. 
These goes together on NSC: buildtool-easybuild/4.8.0-hpce082752a2 GCC/11.3.0 OpenMPI/4.1.4 Python/3.10.4 SciPy-bundle/2022.05 matplotlib/3.5.2 Tkinter/3.10.4

I need: numba on NSC, so maybe a venv could be created for the above Python version?

**Comment by bbrydsoe** [comment]
These are the options on NSC:

Python 3.11.5
has pandas, numpy, scipy, jupyterlab
To load : ml buildtool-easybuild/4.8.0-hpce082752a2 GCC/13.2.0 Python/3.11.5 SciPy-bundle/2023.11 JupyterLab/4.2.0

or

Python 3.10.4 
has pandas, numpy, scipy, matplotlib
To load : ml buildtool-easybuild/4.8.0-hpce082752a2  GCC/11.3.0 Python/3.10.4 OpenMPI/4.1.4 SciPy-bundle/2022.05 matplotlib/3.5.2 Tkinter/3.10.4

None has scikit-learn, pytorch, tensorflow, seaborn, numba

**Comment by bclaremar** [comment]
UPPMAX
based on module 3.11.8 and ML we need these in the venv
- spyder
- scikit-build-core cmake
- lightgbm
- mpi4py
- Julia
- xarray

**Comment by bclaremar** [comment]
UPPMAX requirements file is done
continuing with NSC now

**Comment by jayant-yadav** [comment]
I am using :
UPPMAX : Python/3.11.8
HPC2N : Python/3.11.3
LUNARC : Python/3.11.5
NSC : Python/3.11.5


For all 4 centres we need 2 separate envs for tf and torch each. 
python3 -m pip install torch torchvision
python3 -m pip install 'tensorflow[and-cuda]'
This is because they contain conflicting cuda toolkits. PS: they download their own numpy.
I have checked sklearn yet.

**Comment by bclaremar** [comment]
let spyder out for ML/dask
