### ISSUE TITLE
Get the link checker and spell checker working

### ISSUE THREAD

**Issue by bclaremar** [UPPMAX/HPC-python#8]
Can you @richelbilderbeek  please help us.
It never checks the whole tree.
I have tested the settings from docs pages, and progform and R-python-julia courses pages without success!

**Comment by bclaremar** [comment]
I cannot figure out why the spelling worked once but not after that!

**Comment by richelbilderbeek** [comment]
> I cannot figure out why the spelling worked once but not after that!

@bclaremar: Is it the link checker (from the title) or the spelling checker (from this comment) or both not working?

**Comment by bclaremar** [comment]
both!

**Comment by richelbilderbeek** [comment]
Spellchecker seems to works:

```
richel@richel-N141CU:~/GitHubs/HPC-python$ pyspelling -c .spellcheck.yml
Spelling check passed :)
```

and when adding errors to README:

```
richel@richel-N141CU:~/GitHubs/HPC-python$ pyspelling -c .spellcheck.yml
Misspelled words:
<htmlcontent> README.md: html>body>p
--------------------------------------------------------------------------------
aelrguWBEPFEUIP
--------------------------------------------------------------------------------

!!!Spelling check failed!!!
```

Could break spelling CI script by pushing the error.

**Comment by richelbilderbeek** [comment]
Conclusion: spellchecker worked and works :+1:

**Comment by richelbilderbeek** [comment]
Link checker works:

![Screenshot from 2024-05-15 17-45-47](https://github.com/UPPMAX/HPC-python/assets/2098230/b2093049-c9bf-403e-98b4-62ce179cb7c2)

**Comment by richelbilderbeek** [comment]
@bclaremar both tools work perfectly! To be precise: both tools work perfectly **on Markdown** and on the markdown pages in this repo. 

However, as this page is written in ReStructuredText, one needs other CI tools. I don't know which these are.

That concludes my research :+1:
